development:
  dialect: postgres
  datasource: host=localhost dbname=moviebrain user=mbuser password=secret sslmode=disable
  dir: migrations/postgres

production:
  dialect: postgres
  datasource: ${DATABASE_URL}
  dir: migrations/postgres
  table: migrations
